# Generated by Django 5.0 on 2023-12-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0004_remove_useractivity_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
