# Generated by Django 5.0 on 2023-12-22 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0006_useractivity_last_login_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login_date",
        ),
    ]
